add "crucible archive" and "crucible unarchive" commands
- The "archive" command packages a run result from
  /var/lib/crucible/run into a compressed tarball in
  /var/lib/crucible/archive.  It removes all traces of the run result
  from the run directory up successfull packaging.

- The "unarchive" command unpacks a compressed tarball archive from
  /var/lib/crucible/archive and places it back in
  /var/lib/crucible/run.  It removes the archive upon successfull
  unpacking.

diff --git a/bin/_main b/bin/_main
--- a/bin/_main
+++ b/bin/_main
@@ -257,6 +257,139 @@ function post_process_run() {
     return ${RC}
 }
 
+function unarchive_run() {
+    local ARCHIVE ARCHIVE_FILE TMP_ARCHIVE_FILE LINK_ARCHIVE RUN_NAME UNARCHIVE_CMD
+    ARCHIVE=${1}
+
+    if ! echo "${ARCHIVE}" | grep -q "^${var_archive_crucible}"; then
+        ARCHIVE_FILE="${var_archive_crucible}/${ARCHIVE}"
+    else
+        ARCHIVE_FILE="${ARCHIVE}"
+    fi
+
+    if [ ! -e "${ARCHIVE_FILE}" ]; then
+        echo "ERROR: The specified archive does not exit (${ARCHIVE_FILE})"
+        return 1
+    fi
+
+    if [ -d "${ARCHIVE_FILE}" ]; then
+        echo "ERROR: The specified archive is a directory which does not make sense (${ARCHIVE_FILE})"
+        return 1
+    fi
+
+    TMP_ARCHIVE_FILE=$(readlink -e ${ARCHIVE_FILE})
+    LINK_CLEANUP=""
+    if [ "${TMP_ARCHIVE_FILE}" != "${ARCHIVE_FILE}" ]; then
+        echo "The specified archive is a symbolic link (${ARCHIVE_FILE} -> ${TMP_ARCHIVE_FILE})"
+        LINK_CLEANUP=${ARCHIVE_FILE}
+        ARCHIVE_FILE=${TMP_ARCHIVE_FILE}
+    fi
+
+    ARCHIVE_NAME=$(basename ${ARCHIVE_FILE})
+    BASE_DIR=$(dirname ${ARCHIVE_FILE})
+    RUN_NAME=$(echo "${ARCHIVE_NAME}" | sed -e "s/\.tar\.xz//")
+
+    if [ -e "${var_run_crucible}/${RUN_NAME}" ]; then
+        echo "ERROR: There is already a run result at ${var_run_crucible}/${RUN_NAME}"
+        return 1
+    fi
+
+    UNARCHIVE_CMD="unxz --threads=0 --stdout ${ARCHIVE_FILE} | tar --extract --directory=${var_run_crucible}"
+
+    echo "Unpacking archive:"
+    $podman_run --name crucible-unarchive-${SESSION_ID} "${container_common_args[@]}" ${CRUCIBLE_CONTAINER_IMAGE} /bin/bash -c "${UNARCHIVE_CMD}"
+    if [ $? == 0 ]; then
+        echo "${ARCHIVE_FILE} sucessfully unpacked to ${var_run_crucible}/${RUN_NAME}"
+
+        echo "Removing archived data:"
+        echo -e "\t${ARCHIVE_NAME}"
+        rm ${ARCHIVE_FILE}
+        if [ $? != 0 ]; then
+            return 1
+        fi
+
+        if [ -n "${LINK_CLEANUP}" ]; then
+            echo -e "\t${LINK_CLEANUP} (symbolic link)"
+            rm ${LINK_CLEANUP}
+            if [ $? != 0 ]; then
+                return 1
+            fi
+        fi
+    else
+        echo "ERROR: Failed to unpack ${ARCHIVE_FILE} to ${var_run_crucible}/${RUN_NAME}"
+        return 1
+    fi
+
+    return 0
+}
+
+function archive_run() {
+    local RUN RUN_DIR TMP_RUN_DIR LINK_CLEANUP RUN_NAME ARCHIVE_NAME ARCHIVE_CMD
+    RUN=${1}
+
+    if ! echo "${RUN}" | grep -q "^${var_run_crucible}"; then
+        RUN_DIR="${var_run_crucible}/${RUN}"
+    else
+        RUN_DIR="${RUN}"
+    fi
+
+    if [ ! -e "${RUN_DIR}" ]; then
+        echo "ERROR: The specified run does not exist (${RUN_DIR})"
+        return 1
+    fi
+
+    if [ ! -d "${RUN_DIR}" ]; then
+        echo "ERROR: The specified run is not a directory as expected (${RUN_DIR})"
+        return 1
+    fi
+
+    TMP_RUN_DIR=$(readlink -e ${RUN_DIR})
+    LINK_CLEANUP=""
+    if [ "${TMP_RUN_DIR}" != "${RUN_DIR}" ]; then
+        echo "The specified run directory is a symbolic link (${RUN_DIR} -> ${TMP_RUN_DIR})"
+        LINK_CLEANUP=${RUN_DIR}
+        RUN_DIR=${TMP_RUN_DIR}
+    fi
+
+    RUN_NAME=$(basename ${RUN_DIR})
+    BASE_DIR=$(dirname ${RUN_DIR})
+    ARCHIVE_NAME="${RUN_NAME}.tar.xz"
+
+    if [ -e "${var_archive_crucible}/${ARCHIVE_NAME}" ]; then
+        echo "ERROR: There is already an archive at ${var_archive_crucible}/${ARCHIVE_NAME}"
+        return 1
+    fi
+
+    ARCHIVE_CMD="pushd ${BASE_DIR} > /dev/null && tar --create ${RUN_NAME} | xz --threads=0 --stdout > ${var_archive_crucible}/${ARCHIVE_NAME}"
+
+    echo "Creating archive:"
+    $podman_run --name crucible-archive-${SESSION_ID} "${container_common_args[@]}" ${CRUCIBLE_CONTAINER_IMAGE} /bin/bash -c "${ARCHIVE_CMD}"
+    if [ $? == 0 ]; then
+        echo "${RUN_DIR} successfully archived to ${var_archive_crucible}/${ARCHIVE_NAME}"
+
+        echo "Removing non-archived data:"
+
+        echo -e "\t${RUN_DIR}"
+        rm -Rf "${RUN_DIR}"
+        if [ $? != 0 ]; then
+            return 1
+        fi
+
+        if [ -n "${LINK_CLEANUP}" ]; then
+           echo -e "\t${LINK_CLEANUP} (symbolic link)"
+           rm ${LINK_CLEANUP}
+           if [ $? != 0 ]; then
+               return 1
+           fi
+        fi
+    else
+        echo "ERROR: Failed to archive ${RUN_DIR} to ${var_archive_crucible}/${ARCHIVE_NAME}"
+        return 1
+    fi
+
+    return 0
+}
+
 EXIT_VAL=0
 
 if [ "${1}" == "log" ]; then
@@ -611,6 +744,14 @@ elif [ "${1}" == "notify" ]; then
         echo "ERROR: unsupported 'notify' argument [${1}]"
         EXIT_VAL=1
     fi
+elif [ "${1}" == "archive" ]; then
+    shift
+    archive_run "${1}"
+    EXIT_VAL=$?
+elif [ "${1}" == "unarchive" ]; then
+    shift
+    unarchive_run "${1}"
+    EXIT_VAL=$?
 elif [ "${1}" == "wrapper" ]; then
     shift
     $podman_run --name crucible-wrapper-${SESSION_ID} "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $@
