add optional run completion notifications using the ntfy utility
- see https://github.com/dschep/ntfy for details on how to configure
  ntfy and the supported backends (ie. the different places that you
  can send the notifications)

diff --git a/bin/_main b/bin/_main
--- a/bin/_main
+++ b/bin/_main
@@ -399,6 +399,7 @@ elif [ "${1}" == "postprocess" ]; then
     post_process_run "${base_run_dir}"
     EXIT_VAL=$?
 elif [ "${1}" == "run" ]; then
+    arg_list="$@"
     shift
     benchmark=${1}
     shift
@@ -566,6 +567,33 @@ elif [ "${1}" == "run" ]; then
         if [ ${EXIT_VAL} == 0 ]; then
             EXIT_VAL=${RC}
         fi
+    fi
+
+    send_notification "Finished run command '${arg_list}' with return value '${EXIT_VAL}'.  Results are available in '${base_run_dir}'."
+    RC=$?
+    if [ ${EXIT_VAL} == 0 ]; then
+        EXIT_VAL=${RC}
+    fi
+elif [ "${1}" == "notify" ]; then
+    shift
+    ntfy_doc_url="https://github.com/dschep/ntfy"
+    if [ "${1}" == "config" ]; then
+        shift
+        echo "Currently notification configuration is a manual process where the user must create ${USER_STORE}/ntfy.yml with at least one backend.  See ${ntfy_doc_url} for details."
+        EXIT_VAL=0
+    elif [ "${1}" == "test" ]; then
+        shift
+
+        if [ ! -e ${USER_STORE}/ntfy.yml ]; then
+            echo "ERROR: You must configure at least one notification backend in ${USER_STORE}/ntfy.yml.  See ${ntfy_doc_url} for details."
+            EXIT_VAL=1
+        else
+            send_notification "notification test"
+            EXIT_VAL=$?
+        fi
+    else
+        echo "ERROR: unsupported 'notify' argument [${1}]"
+        EXIT_VAL=1
     fi
 elif [ "${1}" == "wrapper" ]; then
     shift
diff --git a/bin/base b/bin/base
--- a/bin/base
+++ b/bin/base
@@ -118,3 +118,26 @@ function root_or_die {
         exit_error "You must run this as root, exiting" $EC_FAIL_USER
     fi
 }
+
+function send_notification {
+    local message="$@"
+    local RC
+
+    if [ ! -e ${USER_STORE}/ntfy.yml ]; then
+        # notifications via ntfy are not configured
+        return 0
+    fi
+
+    ${podman_run} --name crucible-send-notification-${SESSION_ID} ${container_common_args[@]} $CRUCIBLE_CONTAINER_IMAGE \
+                  ntfy \
+                  -c ${USER_STORE}/ntfy.yml \
+                  -t "Crucible Notification from $(hostname) at $(get_timestamp)" \
+                  send "${message}"
+    RC=$?
+
+    if [ ${RC} != 0 ]; then
+        echo "ERROR: Failed to send notification"
+    fi
+
+    return ${RC}
+}
