lots of changes to support multi-opensearch
-not complete

diff --git a/bin/_main b/bin/_main
--- a/bin/_main
+++ b/bin/_main
@@ -95,8 +95,9 @@ elif [ "${1}" == "get" ]; then
             EXIT_VAL=$?
         elif [ "${1}" == "metric" ]; then
             shift
-            get_metric_cmd="${CRUCIBLE_HOME}/subprojects/core/CommonDataModel/queries/cdmq/get-metric-data.sh"
-            ${podman_run} --name crucible-get-metric-${SESSION_ID} "${container_common_args[@]}" "${container_rs_args[@]}" ${CRUCIBLE_CONTROLLER_IMAGE} ${get_metric_cmd} "$@"
+            cdm_query_opt=$(${CRUCIBLE_HOME}/bin/manage_instances.py --cfg ${INSTANCES_CFG} query-opt)
+            cdm_query_cmd="${CRUCIBLE_HOME}/subprojects/core/CommonDataModel/queries/cdmq/get-metric-data.sh $@ $cdm_query_opt"
+            ${podman_run} --name crucible-get-metric-${SESSION_ID} "${container_common_args[@]}" "${container_rs_args[@]}" ${CRUCIBLE_CONTROLLER_IMAGE} ${cdm_query_cmd}
             EXIT_VAL=$?
         else
             echo "ERROR: unsupported 'get' argument [${1}]"
@@ -105,17 +106,155 @@ elif [ "${1}" == "get" ]; then
     fi
 elif [ "${1}" == "rm" ]; then
     shift
+    instance=""
+    # This is an optional positional argument for 'crucible rm', which overrides the
+    # default opensearch instance when deleting a run (default is whatever instance
+    # is used for indexing).
+    if ! [[ "${1}" =~ ^-- ]]; then
+        instance=${1}
+        shift
+    fi
+
+    # Get the options needed to delete the documents (the host and optional password
+    # information for the default opensearch instance for indexing)
+    cdmver_opt=""
+    access_opt=""
+
+    if [ "$instance" = "" ]; then
+        instance=$(${podman_run}\
+            --name crucible-manage-instances--${SESSION_ID}\
+            ${container_common_args[@]}\
+            ${CRUCIBLE_CONTROLLER_IMAGE}\
+            ${CRUCIBLE_HOME}/bin/manage_instances.py\
+            --cfg ${INSTANCES_CFG}\
+            index-instance)
+    fi
+    echo "instance: [$instance]"
+    cdmver_opt=$(${podman_run}\
+        --name crucible-manage-instances--${SESSION_ID}\
+        ${container_common_args[@]}\
+        ${CRUCIBLE_CONTROLLER_IMAGE}\
+        ${CRUCIBLE_HOME}/bin/manage_instances.py\
+        --cfg ${INSTANCES_CFG}\
+        instance-cdmver-opt --name ${instance})
+    echo "found cdmver [$cdmver_opt] for instance [$instance]"
+    access_opt=$(${podman_run}\
+        --name crucible-manage-instances--${SESSION_ID}\
+        ${container_common_args[@]}\
+        ${CRUCIBLE_CONTROLLER_IMAGE}\
+        ${CRUCIBLE_HOME}/bin/manage_instances.py\
+        --cfg ${INSTANCES_CFG}\
+        instance-host-access-opt --name ${instance})
+
     if start_opensearch; then
-       rm_result_cmd="${CRUCIBLE_HOME}/subprojects/core/CommonDataModel/queries/cdmq/delete-run.sh"
-       ${podman_run} --name crucible-rm-result-${SESSION_ID} "${container_common_args[@]}" "${container_rs_args[@]}" ${CRUCIBLE_CONTROLLER_IMAGE} ${rm_result_cmd} "$@"
+        # Delete the run
+        ${podman_run}\
+            --name crucible-manage-instances--${SESSION_ID}\
+            ${container_common_args[@]}\
+            ${CRUCIBLE_CONTROLLER_IMAGE}\
+            ${CRUCIBLE_HOME}/subprojects/core/CommonDataModel/queries/cdmq/delete-run.sh\
+            ${access_opt} ${cdmver_opt} "$@"
+        RC=$?
     fi
     EXIT_VAL=$?
 elif [ "${1}" == "index" ]; then
     shift
-    if start_opensearch; then
-        base_run_dir=$(echo "$@" | sed -e "s/--base-run-dir\(\s\+\|=\)//")
-        index_run "$base_run_dir"
+    instance=""
+    base_run_dir=""
+    # There is an optional positional argument for which overrides the
+    # default opensearch instance.  This argument must come immediately
+    # after "crucible index" and before any arguments passed to rickshaw
+    # or CDM.  We need to figure out if the optional
+    # argument is here, or the arguments are all for rickshaw/cdm utils.
+    # Just checking for lack of '--' in the
+    # argument and assuming it is an argument to be passed to rickshaw/cdm
+    # does not work here because of previous work to allow
+    # skipping "--base-run-dir" and only specifying the run directory.
+    if [ $# -eq 1 ]; then
+        # There is only 1 argument, and the only two valid options are:
+        # <dir>
+        # --base-run-dir=<dir>
+        # and there is no optional argument to sopeficy the instance
+        base_run_dir=$(echo "${1}" | sed -e "s/--base-run-dir\(\s\+\|=\)//")
+        shift
+    elif [ $# -eq 2 ]; then
+        # There are only 2 arguments...
+        if [[ "${1}" =~ ^-- ]]; then
+            # ...and the first argument starts
+            # with '--', so it must be --base-run-dir and <dir>
+            # and the optional argument to specify the instance is
+            # not present
+            shift
+            base_run_dir=${1}
+            shift
+        else
+            # ...and the first argument does not start
+            # with '--', so the first argument must be the optional
+            # argument speficying the instance to use, and the second
+            # argument is the <dir>
+            instance=${1}
+            shift
+            base_run_dir=$(echo "${1}" | sed -e "s/--base-run-dir\(\s\+\|=\)//")
+            shift
+        fi
+    elif [ $# -eq 3 ]; then
+        # There are 3 agruments, therefore it must be:
+        # <instance>
+        # --base-run-dir
+        # <dir>
+        instance=${1}
+        shift; shift
+        base_run_dir=${1}
+        shift
     fi
+
+    if [ "$instance" = "" ]; then
+        # Get the default instance to use
+        instance=$(${podman_run}\
+            --name crucible-manage-instances--${SESSION_ID}\
+            ${container_common_args[@]}\
+            ${CRUCIBLE_CONTROLLER_IMAGE}\
+            ${CRUCIBLE_HOME}/bin/manage_instances.py\
+            --cfg ${INSTANCES_CFG}\
+            index-instance)
+    fi
+    echo "instance: [$instance]"
+
+    cdmver_opt=$(${podman_run}\
+        --name crucible-manage-instances--${SESSION_ID}\
+        ${container_common_args[@]}\
+        ${CRUCIBLE_CONTROLLER_IMAGE}\
+        ${CRUCIBLE_HOME}/bin/manage_instances.py\
+        --cfg ${INSTANCES_CFG}\
+        instance-cdmver-opt --name ${instance})
+    echo "found cdmver [$cdmver_opt] for instance [$instance]"
+    access_opt=$(${podman_run}\
+        --name crucible-manage-instances--${SESSION_ID}\
+        ${container_common_args[@]}\
+        ${CRUCIBLE_CONTROLLER_IMAGE}\
+        ${CRUCIBLE_HOME}/bin/manage_instances.py\
+        --cfg ${INSTANCES_CFG}\
+        instance-host-access-opt --name ${instance})
+    if [ "$access_opt" == "" ]; then
+        echo "ERROR: access informaiton for Opensearch instance ${instance} was empty.  Did you use a valid instance?"
+        exit 1
+    fi
+    if [ "$cdmver_opt" == "" ]; then
+        echo "ERROR: CDM version informaiton for Opensearch instance ${instance} was empty.  Did you use a valid instance?"
+        exit 1
+    fi
+
+    if start_opensearch; then
+        index_run "${access_opt}" "${cdmver_opt}" "$base_run_dir"
+    fi
+        ## Delete the run
+        #${podman_run}\
+            #--name crucible-manage-instances--${SESSION_ID}\
+            #${container_common_args[@]}\
+            #${CRUCIBLE_CONTROLLER_IMAGE}\
+            #${CRUCIBLE_HOME}/subprojects/core/CommonDataModel/queries/cdmq/delete-run.sh\
+            #${access_opt} ${cdmver_opt} "$@"
+        RC=$?
     EXIT_VAL=$?
 elif [ "${1}" == "extract" ]; then
     shift
diff --git a/bin/base b/bin/base
--- a/bin/base
+++ b/bin/base
@@ -485,16 +485,23 @@ function post_process_run() {
 }
 
 function index_run() {
-    local rs_index_cmd cdm_query_cmd
+    local rs_gendocs_opt rs_gendocs_cmd
+    local cdm_index_opt cdm_index_cmd
     local run_json this_id RUN_DIR
     local post_process_fail RC result_summary
+    local access_opt cdmver_opt
 
+    access_opt=${1}
+    echo "access_opt: [$access_opt]"
+    shift
+    cdmver_opt=${1}
+    echo "cdmver_opt: [$cdmver_opt]"
+    shift
     RUN_DIR=${1}
-    echo "Benchmark result is in ${RUN_DIR}"
+    echo "RUN_DIR: [$RUN_DIR]"
     shift
 
-    rs_index_cmd="${CRUCIBLE_HOME}/subprojects/core/rickshaw/rickshaw-index\
-      --base-run-dir=${RUN_DIR}"
+    echo "Benchmark result is in ${RUN_DIR}"
 
     start_httpd
     RC=$?
@@ -513,10 +520,32 @@ function index_run() {
         return ${RC}
     fi
 
-    ${podman_run} --name crucible-rickshaw-index-${SESSION_ID} "${container_common_args[@]}" "${container_rs_args[@]}" ${CRUCIBLE_CONTROLLER_IMAGE} ${rs_index_cmd}
+    # Generate the CDM documents
+    ${podman_run}\
+        --name crucible-rickshaw-gen-docs-${SESSION_ID}\
+        "${container_common_args[@]}"\
+        "${container_rs_args[@]}"\
+        ${CRUCIBLE_CONTROLLER_IMAGE}\
+        ${CRUCIBLE_HOME}/subprojects/core/rickshaw/rickshaw-gen-docs\
+        --base-run-dir=${RUN_DIR} ${cdmver_opt}
     RC=$?
     if [ ${RC} == 0 ]; then
-        echo "Benchmark result now in OpenSearch, localhost:9200"
+        echo "Opensearch documents have been created"
+        RC=$?
+    else
+        echo "ERROR: Could not generate OpenSearch documents [rc=${RC}]"
+    fi
+
+    # Index the documents
+    ${podman_run}\
+        --name crucible-cdm-index-${SESSION_ID}\
+        "${container_common_args[@]}"\
+        ${CRUCIBLE_CONTROLLER_IMAGE}\
+        ${CRUCIBLE_HOME}/subprojects/core/CommonDataModel/queries/cdmq/add-run.sh\
+        --dir ${RUN_DIR}/run/opensearch $access_opt
+    RC=$?
+    if [ ${RC} == 0 ]; then
+        echo "Benchmark result now in OpenSearch, using ${access_opt} $cdmver_opt" | sed -e 's/--userpass\s\S*\s//'
         RC=$?
     else
         echo "ERROR: Could not index result into OpenSearch [rc=${RC}]"
@@ -527,8 +556,10 @@ function index_run() {
 
 function get_result_backend() {
     local RC
+    local cdm_query_opt cdm_query_cmd
 
-    cdm_query_cmd="${CRUCIBLE_HOME}/subprojects/core/CommonDataModel/queries/cdmq/get-result-summary.sh $@"
+    cdm_query_opt=$(${podman_run} --name crucible-get-result-opt-${SESSION_ID} "${container_common_args[@]}" "${container_rs_args[@]}" ${CRUCIBLE_CONTROLLER_IMAGE} ${CRUCIBLE_HOME}/bin/manage_instances.py --cfg ${INSTANCES_CFG} query-opt)
+    cdm_query_cmd="${CRUCIBLE_HOME}/subprojects/core/CommonDataModel/queries/cdmq/get-result-summary.sh $@ $cdm_query_opt"
     ${podman_run} --name crucible-get-result-${SESSION_ID} "${container_common_args[@]}" "${container_rs_args[@]}" ${CRUCIBLE_CONTROLLER_IMAGE} ${cdm_query_cmd}
     RC=$?
     return ${RC}
