Move run processing code into standalone function
- Allow for later reuse as a stand along run processor

diff --git a/bin/_main b/bin/_main
--- a/bin/_main
+++ b/bin/_main
@@ -108,6 +108,72 @@ function init_es() {
     fi
 }
 
+function post_process_run() {
+    local RUN_DIR=${1}
+    shift
+
+    rs_pp_b_cmd="${CRUCIBLE_HOME}/subprojects/core/rickshaw/rickshaw-post-process-bench\
+      --base-run-dir=${RUN_DIR}"
+    rs_pp_t_cmd="${CRUCIBLE_HOME}/subprojects/core/rickshaw/rickshaw-post-process-tools\
+      --base-run-dir=${RUN_DIR}"
+    rs_pp_c_cmd="${CRUCIBLE_HOME}/subprojects/core/rickshaw/rickshaw-post-process-consolidate\
+      --base-run-dir=${RUN_DIR}"
+    rs_export_cmd="${CRUCIBLE_HOME}/subprojects/core/rickshaw/rickshaw-export\
+      --base-run-dir=${RUN_DIR}"
+
+    start_redis
+    start_httpd
+    start_es
+
+    $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_pp_b_cmd && \
+        $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_pp_t_cmd && \
+        $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_pp_c_cmd && \
+        echo "Benchmark result is in ${RUN_DIR}" && \
+        init_es
+
+    if [ $RET_VAL != 0 ]; then
+        echo "ERROR: Failed to start and initialize ES stack"
+        return
+    fi
+
+    result_dumper=cat
+    result_json="${RUN_DIR}/run/rickshaw-result.json"
+    if [ ! -f $result_json ]; then
+        result_dumper=xzcat
+        result_json="${RUN_DIR}/run/rickshaw-result.json.xz"
+    fi
+
+    if [ -f $result_json ]; then
+        $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_export_cmd
+        RET_VAL=$?
+        if [ $RET_VAL -eq 0 ]; then
+            echo "Benchmark result now in elastic, localhost:9200"
+            this_id=`$podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE ${result_dumper} ${result_json} | jq -r '."run-id"'`
+            if [ ! -z "$this_id" ]; then
+                cdm_query_cmd="${CRUCIBLE_HOME}/subprojects/core/CommonDataModel/queries/cdmq/get-result-summary.sh"
+                cdm_query_cmd+=" --run=$this_id"
+                echo "Generating benchmark summary report"
+                sleep 5 # ES may take 5 seconds to have data ready (from a setting which can vastly improve index operations)
+                $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $cdm_query_cmd | tee "${RUN_DIR}/run/result-summary.txt"
+                RET_VAL=$?
+                if [ $RET_VAL -eq 0 ]; then
+                    echo
+                    echo "Benchmark summary is complete and can be found in:"
+                    echo "${RUN_DIR}/run/result-summary.txt"
+                else
+                    echo "ERROR: Could not generate benchmark summary"
+                fi
+            else
+                echo "ERROR: Could not get the run-id from this run"
+            fi
+        else
+            echo "ERROR: Could not index result into elasticsearch"
+        fi
+    else
+        echo "ERROR: Could not find result json '${result_json}'"
+    fi
+}
+
 if [ "${1}" == "log" ]; then
     shift
     crucible_log ${1} ${LOG_DB}
@@ -279,61 +345,9 @@ elif [ "${1}" == "run" ]; then
       --tools-dir=${CRUCIBLE_HOME}/subprojects/tools\
       --base-run-dir=$base_run_dir\
       ${passthru_args[@]}"
-    rs_pp_b_cmd="${CRUCIBLE_HOME}/subprojects/core/rickshaw/rickshaw-post-process-bench\
-      --base-run-dir=$base_run_dir"
-    rs_pp_t_cmd="${CRUCIBLE_HOME}/subprojects/core/rickshaw/rickshaw-post-process-tools\
-      --base-run-dir=$base_run_dir"
-    rs_pp_c_cmd="${CRUCIBLE_HOME}/subprojects/core/rickshaw/rickshaw-post-process-consolidate\
-      --base-run-dir=$base_run_dir"
-    rs_export_cmd="${CRUCIBLE_HOME}/subprojects/core/rickshaw/rickshaw-export\
-      --base-run-dir=$base_run_dir"
-    start_redis
-    start_httpd
-    start_es
     $podman_run --name crucible-run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_run_cmd
-    if [ $RET_VAL -eq 0 ]; then
-        $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_pp_b_cmd && \
-        $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_pp_t_cmd && \
-        $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_pp_c_cmd && \
-            echo "Benchmark result is in $base_run_dir" && \
-        init_es
-        result_dumper=cat
-        result_json="$base_run_dir/run/rickshaw-result.json"
-        if [ ! -f $result_json ]; then
-            result_dumper=xzcat
-            result_json="$base_run_dir/run/rickshaw-result.json.xz"
-        fi
-        if [ -f $result_json -a $RET_VAL -eq 0 ]; then
-            $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_export_cmd
-            RET_VAL=$?
-            if [ $RET_VAL -eq 0 ]; then
-                echo "Benchmark result now in elastic, localhost:9200"
-                this_id=`$podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE ${result_dumper} ${result_json} | jq -r '."run-id"'`
-                if [ ! -z "$this_id" ]; then
-                    cdm_query_cmd="${CRUCIBLE_HOME}/subprojects/core/CommonDataModel/queries/cdmq/get-result-summary.sh"
-                    cdm_query_cmd+=" --run=$this_id"
-                    echo "Generating benchmark summary report"
-                    sleep 5 # ES may take 5 seconds to have data ready (from a setting which can vastly improve index operations)
-                    $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $cdm_query_cmd | tee "$base_run_dir/run/result-summary.txt"
-                    RET_VAL=$?
-                    if [ $RET_VAL -eq 0 ]; then
-                        echo
-                        echo "Benchmark summary is complete and can be found in:"
-                        echo "$base_run_dir/run/result-summary.txt"
-                    else
-                        echo "ERROR: Could not generate benchmark summary"
-                    fi
-                else
-                    echo "ERROR: Could not get the run-id from this run"
-                fi
-            else
-                echo "ERROR: Could not index result into elasticsearch"
-            fi
-        fi
-    else
-        echo "crucible run failed:"
-        echo $podman_run --name crucible-run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_run_cmd
-    fi
+
+    post_process_run ${base_run_dir}
 
     if [ "$CRUCIBLE_USE_LOGGER" == "1" ]; then
         echo "Archiving crucible log to ${base_run_dir}"
