add the ability to stop services
- all services now have both a start and stop capability

- podman status checks are changed slightly since they are serving
  multiple purposes now

diff --git a/bin/_main b/bin/_main
--- a/bin/_main
+++ b/bin/_main
@@ -73,6 +73,23 @@ function start_httpd() {
         RC=$?
         if [ ${RC} != 0 ]; then
             echo "ERROR: Could not start httpd"
+        else
+            echo "Successfully started httpd"
+        fi
+    fi
+    return ${RC}
+}
+
+function stop_httpd() {
+    local RC=0
+    echo -n "Checking for httpd"
+    if podman_running crucible-httpd; then
+        ${podman_stop} crucible-httpd > /dev/null
+        RC=$?
+        if [ ${RC} != 0 ]; then
+            echo "ERROR: Could not stop httpd"
+        else
+            echo "Successfully stopped httpd"
         fi
     fi
     return ${RC}
@@ -88,6 +105,23 @@ function start_redis() {
         RC=$?
         if [ ${RC} != 0 ]; then
             echo "ERROR: Could not start redis"
+        else
+            echo "Successfully started redis"
+        fi
+    fi
+    return ${RC}
+}
+
+function stop_redis() {
+    local RC=0
+    echo -n "Checking for redis"
+    if podman_running crucible-redis; then
+        ${podman_stop} crucible-redis > /dev/null
+        RC=$?
+        if [ ${RC} != 0 ]; then
+            echo "ERROR: Could not stop redis"
+        else
+            echo "Successfully stopped redis"
         fi
     fi
     return ${RC}
@@ -135,8 +169,24 @@ function start_es() {
                 echo "ERROR: Elasticsearch failed to launch properly"
                 RC=1
             else
+                echo "Successfully started elasticsearch"
                 RC=0
             fi
+        fi
+    fi
+    return ${RC}
+}
+
+function stop_es() {
+    local RC=0
+    echo -n "Checking for elasticsearch"
+    if podman_running crucible-es; then
+        ${podman_stop} crucible-es > /dev/null
+        RC=$?
+        if [ ${RC} != 0 ]; then
+            echo "ERROR: Could not stop elasticsearch"
+        else
+            echo "Successfully stopped elasticsearch"
         fi
     fi
     return ${RC}
@@ -463,6 +513,21 @@ elif [ "${1}" == "start" ]; then
     elif [ "${1}" == "redis" ]; then
         shift
         start_redis
+        EXIT_VAL=$?
+    fi
+elif [ "${1}" == "stop" ]; then
+    shift
+    if [ "${1}" == "httpd" ]; then
+        shift
+        stop_httpd
+        EXIT_VAL=$?
+    elif [ "${1}" == "es" ]; then
+        shift
+        stop_es
+        EXIT_VAL=$?
+    elif [ "${1}" == "redis" ]; then
+        shift
+        stop_redis
         EXIT_VAL=$?
     fi
 elif [ "${1}" == "get" ]; then
