Add result summary generation

diff --git a/bin/_main b/bin/_main
--- a/bin/_main
+++ b/bin/_main
@@ -230,13 +230,32 @@ elif [ "${1}" == "run" ]; then
             $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_pp_t_cmd && \
             $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_pp_c_cmd && \
 	        echo "Benchmark result is in $base_run_dir" && \
-            $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $es_init_cmd && \
-            $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_export_cmd
+            $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $es_init_cmd
             RET_VAL=$?
-            if [ $RET_VAL -eq 0 ]; then
-	            echo "Benchmark result now in elastic, localhost:9200"
-            fi
-	    fi
+            if [ -f "$base_run_dir/run/rickshaw-result.json" -a $RET_VAL -eq 0 ]; then
+                $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $rs_export_cmd
+                RET_VAL=$?
+                if [ $RET_VAL -eq 0 ]; then
+	                echo "Benchmark result now in elastic, localhost:9200"
+                    run_id=`jq -r '."run-id"' "$base_run_dir/run/rickshaw-result.json"`
+                    cdm_query_cmd="${CRUCIBLE_HOME}/subprojects/core/CommonDataModel/queries/cdmq/get-result-summary.sh"
+                    cdm_query_cmd+=" --run=$run_id"
+                    echo "Generating benchmark summary report"
+                    sleep 5 # ES may take 5 seconds to have data ready (from a setting which can vastly improve index operations)
+                    $podman_run "${container_common_args[@]}" "${container_rs_args[@]}" $CRUCIBLE_CONTAINER_IMAGE $cdm_query_cmd | tee "$base_run_dir/run/result-summary.txt"
+                    RET_VAL=$?
+                    if [ $RET_VAL -eq 0 ]; then
+                        echo
+                        echo "Benchmark summary is complete and can be found in:"
+                        echo "$base_run_dir/run/result-summary.txt"
+                    else
+                        echo "ERROR: Could not generate benchmark summary"
+                    fi
+                else
+                    echo "ERROR: Could not index result into elasticsearch"
+                fi
+	        fi
+        fi
     fi
 elif [ "${1}" == "wrapper" ]; then
     shift
